---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kcp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem
